### ISSUE TITLE
There exists a need for configuring elements in Grype, such as enabling search of external sources

### ISSUE THREAD

**Issue by nostra** [openclarity/grype-server#9]
Due to an open issue at Grype ( https://github.com/anchore/grype/issues/1014 ) I want to configure the Grype server with: 
```
external-sources:
  enable: true
  maven:
    search-upstream-by-sha1: true
    base-url: https://search.maven.org/solrsearch/select
```

This (probably) entails setting this value to true here: https://github.com/Portshift/grype-server/blob/main/grype-server/pkg/scanner/scanner.go#L146 

Supporting configuration of Grype elements would alleviate the problem. I suspect that there are more elements that would benefit from being configurable when I look at #7 

Ideally the configuration format would be the same as for Grype itself, but that might not be feasible or convenient. Also, I do not have a full overview over all elements that would benefit from configuration. 

My isolated problem can be solved by making `SearchMavenUpstream` configurable.
